# Generated by Django 4.1.3 on 2023-01-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_usuarios_auth_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='auth_id',
        ),
    ]
