# Generated by Django 4.1.3 on 2023-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0002_factura_alumbrado_valor_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='pago_total',
            new_name='valor_recargo',
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_total',
            field=models.FloatField(null=True),
        ),
    ]
