# Generated by Django 4.1.3 on 2023-01-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0003_rename_pago_total_factura_valor_recargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='lys_valor_total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='valor_recargo',
        ),
    ]
