# Generated by Django 4.1.4 on 2022-12-31 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0002_ju'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_vinculación', models.DateField(default=datetime.date(2022, 12, 31))),
                ('estado_contrato', models.CharField(default='activo', max_length=20)),
                ('ciudad', models.CharField(default='Cali', max_length=30)),
                ('direccion', models.CharField(max_length=40)),
                ('estrato', models.CharField(max_length=10)),
                ('uso', models.CharField(default='Domestico', max_length=20)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
            ],
            options={
                'db_table': 'Contrato',
            },
        ),
    ]
