# Generated by Django 4.1.4 on 2022-12-31 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_vinculación',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 22, 48, 21, 236635, tzinfo=datetime.timezone.utc)),
        ),
    ]
