# Generated by Django 4.1.4 on 2022-12-31 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contrato', '0002_alter_contrato_fecha_vinculación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_vinculación',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 23, 53, 39, 214664, tzinfo=datetime.timezone.utc)),
        ),
    ]
