# Generated by Django 4.1.4 on 2023-01-01 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contrato', '0003_alter_contrato_fecha_vinculación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_vinculación',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 19, 5, 4, 285007, tzinfo=datetime.timezone.utc)),
        ),
    ]
