# Generated by Django 4.1.3 on 2023-01-02 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contrato', '0005_alter_contrato_fecha_vinculación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_vinculación',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 20, 49, 35, 114667, tzinfo=datetime.timezone.utc)),
        ),
    ]
