# Generated by Django 4.1.3 on 2023-01-03 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contrato', '0009_alter_contrato_fecha_vinculación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_vinculación',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 2, 17, 35, 144039, tzinfo=datetime.timezone.utc)),
        ),
    ]
