# Generated by Django 4.1.3 on 2023-01-30 18:40

import Tarjetas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0005_alter_usuarios_apellido_alter_usuarios_barrio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_tarjeta', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.CharField(max_length=13, unique=True, validators=[Tarjetas.models.validar_numero_tarjeta])),
                ('fecha_vencimiento', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta_debito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('num_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarjetas.tarjetas', unique=True)),
            ],
            options={
                'db_table': 'Debito',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta_credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.FloatField()),
                ('num_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarjetas.tarjetas', unique=True)),
            ],
            options={
                'db_table': 'Credito',
            },
        ),
        migrations.CreateModel(
            name='MiTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarjetas.tarjetas', unique=True)),
            ],
            options={
                'db_table': 'MisTarjetas',
            },
        ),
    ]
