# Generated by Django 4.1.3 on 2023-01-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetas',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='tarjetas',
            name='password',
        ),
    ]
