# Generated by Django 4.1.3 on 2023-01-30 23:49

import Tarjetas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0002_remove_tarjetas_banco_remove_tarjetas_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='numero_tarjeta',
            field=models.CharField(max_length=16, unique=True, validators=[Tarjetas.models.validar_numero_tarjeta]),
        ),
    ]
