# Generated by Django 4.1.3 on 2023-01-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0003_alter_tarjetas_numero_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='fecha_vencimiento',
            field=models.CharField(max_length=4),
        ),
    ]
