# Generated by Django 4.1.3 on 2023-01-31 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0003_alter_tarjetas_numero_tarjeta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mitarjeta',
            table='MiTarjeta',
        ),
    ]
