# Generated by Django 4.1.3 on 2023-01-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0004_alter_mitarjeta_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarjeta_credito',
            table='Tarjeta_credito',
        ),
        migrations.AlterModelTable(
            name='tarjeta_debito',
            table='Tarjeta_debito',
        ),
    ]
