# Generated by Django 4.1.3 on 2023-01-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0004_alter_tarjetas_fecha_vencimiento'),
        ('Tarjetas', '0005_alter_tarjeta_credito_table_and_more'),
    ]

    operations = [
    ]
